version: '2'
services:
  app: &app_base
    build: .
    command: bash -lc 'bin/rails db:migrate RAILS_ENV=development && bundle exec rails s -p 3000 -b '0.0.0.0''
    restart: always
    ports:
      - "3000:3000"
volumes:
  db-data:
